import Peer from "https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm";
import{createPose,draw,measure,setMetrics,getCamera}from"./pose.js";
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="./src/lecture.css">');
const $=(s,r=document)=>r.querySelector(s),target=new URLSearchParams(location.search).get("peer"),video=$("video"),canvas=$("canvas"),root=$(".capture-card");let stream,pose,conn,call,last=-1,running=false,lastSent=0;
if(!target){$("#systemStatus").textContent="接続先がありません";$("#startCapture").disabled=true}else $("#systemStatus").textContent="PCへの接続準備完了";
async function cameras(){try{const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==="videoinput");$("#cameraSelect").innerHTML=devices.map((d,i)=>`<option value="${d.deviceId}">${d.label||`カメラ ${i+1}`}</option>`).join("");const back=devices.findIndex(d=>/back|rear|背面|environment/i.test(d.label));if(back>=0)$("#cameraSelect").selectedIndex=back}catch{}}
async function start(){const button=$("#startCapture");try{button.disabled=true;stream=await getCamera({video:{deviceId:$("#cameraSelect").value?{exact:$("#cameraSelect").value}:undefined,facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24}},audio:false});video.srcObject=stream;await video.play();canvas.width=video.videoWidth;canvas.height=video.videoHeight;$(".placeholder",root).classList.add("hidden");pose=await createPose();const peer=new Peer();await new Promise((resolve,reject)=>{peer.on("open",resolve);peer.on("error",reject)});call=peer.call(target,stream);conn=peer.connect(target,{reliable:false});conn.on("open",()=>{$("#statusDot").classList.add("active");$("#systemStatus").textContent="PCへ送信中";button.textContent="接続中";running=true;requestAnimationFrame(loop)});peer.on("error",e=>{$("#systemStatus").textContent=`接続エラー: ${e.type}`})}catch(e){$("#systemStatus").textContent=e.name==="NotAllowedError"?"カメラを許可してください":e.message;button.disabled=false}}
function loop(t){if(!running)return;if(video.readyState>=2&&video.currentTime!==last){last=video.currentTime;pose.detectForVideo(video,t,r=>{const p=r.landmarks?.[0];if(!p)return;draw(canvas,p);const m=measure(p);setMetrics(root,m);if(conn?.open&&t-lastSent>66){conn.send({type:"pose",timestamp:Date.now(),metrics:m,landmarks:p});lastSent=t}})}requestAnimationFrame(loop)}
$("#startCapture").addEventListener("click",start);cameras();navigator.mediaDevices?.addEventListener("devicechange",cameras);
