import Peer from "https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm";
import { createPose, draw, measure, setMetrics, getCamera } from "./pose.js";
document.head.insertAdjacentHTML("beforeend", '<link rel="stylesheet" href="./src/lecture.css"><style>.camera-switcher{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px;padding:5px;background:#111416;border:1px solid var(--line)}.camera-switcher button{padding:13px;background:transparent;color:var(--muted);border:1px solid transparent;font-weight:700}.camera-switcher button.active{background:var(--lime);color:#10130b}</style>');
const $ = (s, r = document) => r.querySelector(s), target = new URLSearchParams(location.search).get("peer"), video = $("video"), canvas = $("canvas"), root = $(".capture-card");
let stream, pose, conn, call, peer, last = -1, running = false, lastSent = 0, facing = "environment", cameraDevices = [];
const switcher = document.createElement("div");
switcher.className = "camera-switcher"; switcher.setAttribute("role", "group"); switcher.setAttribute("aria-label", "iPhoneカメラの向き");
switcher.innerHTML = '<button class="active" data-facing="environment">背面カメラ</button><button data-facing="user">インカメラ</button>';
$(".camera-choice").before(switcher);
if (!target) { $("#systemStatus").textContent = "接続先がありません"; $("#startCapture").disabled = true; } else $("#systemStatus").textContent = "PCへの接続準備完了";
function chooseDevice() { const re = facing === "environment" ? /back|rear|背面|environment/i : /front|facetime|前面|user|インカメラ/i; const match = cameraDevices.find(d => re.test(d.label)); $("#cameraSelect").value = match?.deviceId || ""; }
async function cameras() { try { cameraDevices = (await navigator.mediaDevices.enumerateDevices()).filter(d => d.kind === "videoinput"); $("#cameraSelect").innerHTML = '<option value="">自動選択</option>' + cameraDevices.map((d, i) => `<option value="${d.deviceId}">${d.label || `カメラ ${i + 1}`}</option>`).join(""); chooseDevice(); } catch {} }
function closeConnection() { running = false; stream?.getTracks().forEach(t => t.stop()); call?.close(); conn?.close(); peer?.destroy(); stream = call = conn = peer = null; }
async function start() { const button = $("#startCapture"); try { button.disabled = true; closeConnection(); const deviceId = $("#cameraSelect").value; stream = await getCamera({ video: { ...(deviceId ? { deviceId: { exact: deviceId } } : { facingMode: { ideal: facing } }), width: { ideal: 1280 }, height: { ideal: 720 }, frameRate: { ideal: 24 } }, audio: false }); video.srcObject = stream; await video.play(); canvas.width = video.videoWidth; canvas.height = video.videoHeight; $(".placeholder", root).classList.add("hidden"); await cameras(); pose ??= await createPose(); peer = new Peer(); await new Promise((resolve, reject) => { peer.on("open", resolve); peer.on("error", reject); }); call = peer.call(target, stream); conn = peer.connect(target, { reliable: false }); conn.on("open", () => { $("#statusDot").classList.add("active"); $("#systemStatus").textContent = `${facing === "environment" ? "背面" : "イン"}カメラをPCへ送信中`; button.textContent = "カメラを再接続"; running = true; requestAnimationFrame(loop); }); peer.on("error", e => { $("#systemStatus").textContent = `接続エラー: ${e.type}`; }); } catch (e) { $("#systemStatus").textContent = e.name === "NotAllowedError" ? "カメラを許可してください" : e.message; } finally { button.disabled = false; } }
function loop(t) { if (!running) return; if (video.readyState >= 2 && video.currentTime !== last) { last = video.currentTime; pose.detectForVideo(video, t, result => { const landmarks = result.landmarks?.[0]; if (!landmarks) return; draw(canvas, landmarks); const metrics = measure(landmarks); setMetrics(root, metrics); if (conn?.open && t - lastSent > 66) { conn.send({ type: "pose", timestamp: Date.now(), metrics, landmarks, facing }); lastSent = t; } }); } requestAnimationFrame(loop); }
switcher.addEventListener("click", async event => { const button = event.target.closest("button[data-facing]"); if (!button || button.dataset.facing === facing) return; facing = button.dataset.facing; switcher.querySelectorAll("button").forEach(item => item.classList.toggle("active", item === button)); chooseDevice(); $(".cue", root).textContent = facing === "environment" ? "背面カメラ / 側面撮影" : "インカメラ / 左右反転表示"; if (stream) await start(); });
$("#startCapture").addEventListener("click", start);
$("#cameraSelect").addEventListener("change", () => { const label = $("#cameraSelect").selectedOptions[0]?.textContent || ""; if (/front|facetime|前面|user|インカメラ/i.test(label)) facing = "user"; if (/back|rear|背面|environment/i.test(label)) facing = "environment"; switcher.querySelectorAll("button").forEach(item => item.classList.toggle("active", item.dataset.facing === facing)); });
cameras(); navigator.mediaDevices?.addEventListener("devicechange", cameras);
