import Peer from "https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm";
import{createPose,draw,measure,setMetrics,getCamera}from"./pose.js";
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="./src/lecture.css">');
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="./src/remote-display.css">');
const $=(s,r=document)=>r.querySelector(s),pcRoot=$("[data-camera=pc]"),phoneRoot=$("[data-camera=phone]"),pcVideo=$("video",pcRoot),pcCanvas=$("canvas",pcRoot),phoneVideo=$("video",phoneRoot),phoneCanvas=$("canvas",phoneRoot);let pose,pcStream,pcValues,phoneValues,last=-1,running=false;
const peer=new Peer();let activeCall,activeConnection;
peer.on("open",id=>{const url=new URL("./capture.html",location.href);url.searchParams.set("peer",id);$("#roomCode").textContent=id.slice(-6).toUpperCase();$("#captureLink").href=url.href;$("#qrCode").innerHTML="";new QRCode($("#qrCode"),{text:url.href,width:112,height:112,colorDark:"#0b0d0f",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});$("#systemStatus").textContent="iPhone接続待ち"});
peer.on("call",call=>{activeCall=call;call.answer(new MediaStream());call.on("stream",stream=>{if(activeCall!==call)return;phoneVideo.srcObject=stream;phoneVideo.play();$(".placeholder",phoneRoot).classList.add("hidden");$(".live-badge",phoneRoot).textContent="● LIVE";$(".live-badge",phoneRoot).classList.add("active");$(".cue",phoneRoot).textContent="側面映像を受信中";$("#phoneDot").classList.add("active");$("#phoneState").textContent="Remote Camera接続済み";$("#phoneDetail").textContent="側面の姿勢データを受信しています";updateStatus()});call.on("close",()=>{if(activeCall===call){activeCall=null;phoneDisconnected()}})});
peer.on("connection",conn=>{activeConnection=conn;conn.on("data",data=>{if(activeConnection!==conn||data.type!=="pose")return;phoneValues=data.metrics;phoneCanvas.width=phoneVideo.videoWidth||1280;phoneCanvas.height=phoneVideo.videoHeight||720;draw(phoneCanvas,data.landmarks);setMetrics(phoneRoot,phoneValues);updateCoach()});conn.on("close",()=>{if(activeConnection===conn)activeConnection=null})});peer.on("error",e=>{$("#systemStatus").textContent=`接続エラー: ${e.type}`});
function phoneDisconnected(){phoneVideo.srcObject=null;phoneValues=null;phoneCanvas.getContext("2d").clearRect(0,0,phoneCanvas.width,phoneCanvas.height);$("#phoneDot").classList.remove("active");$("#phoneState").textContent="Remote Cameraが切断されました";$(".live-badge",phoneRoot).textContent="● OFFLINE";$(".live-badge",phoneRoot).classList.remove("active");$(".placeholder",phoneRoot).classList.remove("hidden");$("#statusDot").classList.remove("active");updateStatus()}
function updateStatus(){if(pcStream&&phoneVideo.srcObject){$("#statusDot").classList.add("active");$("#systemStatus").textContent="2視点を解析中"}else if(pcStream)$("#systemStatus").textContent="PCカメラ動作中 / iPhone待ち"}
async function startPc(){const button=$("#startPc");try{button.disabled=true;pcStream?.getTracks().forEach(t=>t.stop());pcStream=await getCamera({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});pcVideo.srcObject=pcStream;await pcVideo.play();pcCanvas.width=pcVideo.videoWidth;pcCanvas.height=pcVideo.videoHeight;$(".placeholder",pcRoot).classList.add("hidden");$(".live-badge",pcRoot).textContent="● LIVE";$(".live-badge",pcRoot).classList.add("active");$(".cue",pcRoot).textContent="正面映像を解析中";pose??=await createPose();running=true;button.textContent="PCカメラを再接続";updateStatus();requestAnimationFrame(loop)}catch(e){$("#systemStatus").textContent=e.name==="NotAllowedError"?"カメラを許可してください":e.message}finally{button.disabled=false}}
function loop(){if(!running)return;if(pcVideo.readyState>=2&&pcVideo.currentTime!==last){last=pcVideo.currentTime;pose.detectForVideo(pcVideo,performance.now(),r=>{const p=r.landmarks?.[0];if(!p)return;draw(pcCanvas,p);pcValues=measure(p);setMetrics(pcRoot,pcValues);updateCoach()})}requestAnimationFrame(loop)}
function updateCoach(){const vals=[pcValues,phoneValues].filter(Boolean);if(!vals.length)return;const knee=Math.round(vals.reduce((s,v)=>s+v.knee,0)/vals.length),trunk=Math.round(vals.reduce((s,v)=>s+v.trunk,0)/vals.length),depth=Math.max(0,Math.min(100,Math.round((170-knee)/.8)));$("#depthValue").textContent=`${depth}%`;const dial=$(".depth-dial");dial.classList.toggle("good",knee<=100&&trunk<=45);dial.classList.toggle("warn",trunk>45);if(trunk>45){$("#coachTitle").textContent="胸を起こしましょう";$("#coachText").textContent="側面視点で体幹の倒れ込みを検出しています。"}else if(knee<=100){$("#coachTitle").textContent="良い深さです";$("#coachText").textContent=vals.length===2?"正面・側面の両視点で動作を確認しています。":"接続中の視点で良好な深さです。"}else{$("#coachTitle").textContent="安定して下降中";$("#coachText").textContent="膝とつま先の方向を揃えて動作を続けてください。"}}
$("#startPc").addEventListener("click",startPc);
