import { createPose, draw, measure, getCamera } from "./pose.js";
document.head.insertAdjacentHTML("beforeend", '<style>.replay-cam{position:relative;margin-top:18px}.replay-section video{width:100%}.replay-cam canvas{position:absolute;inset:0;width:100%;height:100%;transform:scaleX(-1);pointer-events:none}</style>');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={mode:"concurrent",recording:false,startTime:0,rows:[],blobs:{A:null,B:null},toggles:{skeleton:true,trajectory:true,numeric:true,angles:true,target:true}};
const landmarkIndex={wrist:{left:15,right:16},shoulder:{left:11,right:12},hip:{left:23,right:24},knee:{left:25,right:26}};

function asymmetry(p){const pairs=[[11,12],[23,24],[25,26]];return Math.round(pairs.reduce((sum,[l,r])=>sum+Math.abs(p[l].y-p[r].y),0)/pairs.length*1000)/10}
function csvCell(v){const text=typeof v==="string"?v:JSON.stringify(v);return `"${String(text??"").replaceAll('"','""')}"`}
function feedbackVisible(){return state.mode==="concurrent"||state.mode==="terminal"&&!state.recording}

class CameraUnit{
  constructor(id){this.id=id;this.root=$(`[data-camera="${id}"]`);this.video=$("video",this.root);this.canvas=$("canvas",this.root);this.device=$(`#device${id}`);this.view=$(`#view${id}`);this.stream=null;this.pose=null;this.recorder=null;this.chunks=[];this.samples=[];this.trail=[];this.lastTime=-1;this.values=null;this.looping=false}
  async start(){this.stopStream();if(!this.device.value)throw new Error(`Camera ${this.id}を選択してください`);this.stream=await getCamera({video:{deviceId:{exact:this.device.value},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});this.video.srcObject=this.stream;await this.video.play();this.canvas.width=this.video.videoWidth;this.canvas.height=this.video.videoHeight;$(".empty-view",this.root).hidden=true;$(".live-badge",this.root).textContent="● LIVE";$(".live-badge",this.root).classList.add("active");this.viewChanged();this.looping=true;requestAnimationFrame(t=>this.loop(t))}
  stopStream(){this.looping=false;this.stream?.getTracks().forEach(t=>t.stop());this.stream=null}
  viewChanged(){$("header strong",this.root).textContent=this.view.value==="front"?"Front View":"Side View"}
  loop(t){if(!this.looping)return;if(this.video.readyState>=2&&this.video.currentTime!==this.lastTime){this.lastTime=this.video.currentTime;this.pose.detectForVideo(this.video,t,result=>this.update(result,t))}requestAnimationFrame(n=>this.loop(n))}
  update(result,now){const p=result.landmarks?.[0];if(!p)return;const tracked=p[landmarkIndex[$("#trackPoint").value][$ ("#trackSide").value]];this.values={...measure(p),asymmetry:asymmetry(p),trackingX:+tracked.x.toFixed(4),trackingY:+tracked.y.toFixed(4)};this.trail.push({x:tracked.x,y:tracked.y,t:now});this.trail=this.trail.filter(v=>now-v.t<3000);const sample={t:state.recording?now-state.startTime:now,metrics:this.values,landmarks:p.map(v=>({x:+v.x.toFixed(5),y:+v.y.toFixed(5),z:+v.z.toFixed(5),visibility:+(v.visibility??0).toFixed(3)}))};this.samples.push(sample);if(this.samples.length>1800)this.samples.shift();if(state.recording)state.rows.push({timestamp:new Date().toISOString(),elapsed_ms:Math.round(sample.t),camera:this.id,view:this.view.value,...this.values,feedback_condition:$("#condition").value,trial:$("#trialNumber").value,memo:$("#memo").value,landmarks:sample.landmarks});this.render(p);updateChart();updateCount()}
  render(p){const visible=feedbackVisible();const ctx=this.canvas.getContext("2d");ctx.clearRect(0,0,this.canvas.width,this.canvas.height);if(visible&&state.toggles.skeleton)draw(this.canvas,p);if(visible&&state.toggles.trajectory){ctx.strokeStyle="#66e1ef";ctx.lineWidth=4;ctx.beginPath();this.trail.forEach((v,i)=>i?ctx.lineTo(v.x*this.canvas.width,v.y*this.canvas.height):ctx.moveTo(v.x*this.canvas.width,v.y*this.canvas.height));ctx.stroke()}$$('[data-value]',this.root).forEach(el=>{const key=el.dataset.value;el.textContent=visible&&state.toggles.numeric?`${this.values[key]}${key==="asymmetry"?"%":"°"}`:"—"});const target=+$("#targetValue").value,tol=+$("#tolerance").value,inRange=Math.abs(this.values.knee-target)<=tol,pill=$(".target-pill",this.root);pill.hidden=!(visible&&state.toggles.target);pill.classList.toggle("in-range",inRange);$("b",pill).textContent=`${this.values.knee}° / ${target}±${tol}°`;this.canvas.style.opacity=visible&&(state.toggles.skeleton||state.toggles.trajectory||state.toggles.angles)?1:0;$(".camera-values",this.root).style.opacity=visible&&state.toggles.numeric?1:.25}
  beginRecord(){this.chunks=[];const mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/mp4"].find(MediaRecorder.isTypeSupported);this.recorder=new MediaRecorder(this.stream,mime?{mimeType:mime}:undefined);this.recorder.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data)};this.recorder.start(250)}
  finishRecord(){return new Promise(resolve=>{if(!this.recorder||this.recorder.state==="inactive")return resolve(null);this.recorder.onstop=()=>{const blob=new Blob(this.chunks,{type:this.recorder.mimeType});state.blobs[this.id]=blob;resolve(blob)};this.recorder.stop()})}
}
const units=[new CameraUnit("A"),new CameraUnit("B")];

async function devices(request=false){let temporary;if(request)temporary=await getCamera({video:true,audio:false});const list=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==="videoinput");temporary?.getTracks().forEach(t=>t.stop());units.forEach((u,i)=>{const old=u.device.value;u.device.innerHTML=list.map((d,j)=>`<option value="${d.deviceId}">${d.label||`カメラ ${j+1}`}</option>`).join("");u.device.value=list.some(d=>d.deviceId===old)?old:(list[i]?.deviceId||list[0]?.deviceId||"")});if(units[0].device.value===units[1].device.value&&list[1])units[1].device.value=list[1].deviceId;$("#systemStatus").textContent=`${list.length}台のカメラを検出`}
async function startAll(){try{$("#startCameras").disabled=true;await devices(true);if(units[0].device.value===units[1].device.value)throw new Error("Camera A/Bには異なるカメラを選択してください");await Promise.all(units.map(async u=>{u.pose??=await createPose();await u.start()}));$("#statusDot").classList.add("active");$("#systemStatus").textContent="2視点をリアルタイム解析中";$("#startCameras").textContent="再接続"}catch(e){$("#systemStatus").textContent=e.name==="NotAllowedError"?"カメラを許可してください":e.message}finally{$("#startCameras").disabled=false}}

function modeFromCondition(){const c=$("#condition").value;return c==="No BF"?"none":c==="Terminal BF"?"terminal":"concurrent"}
function setMode(mode){state.mode=mode;$$('.feedback-mode button').forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("#condition").value=mode==="none"?"No BF":mode==="terminal"?"Terminal BF":"Concurrent BF";units.forEach(u=>{if(u.values)u.render(u.samples.at(-1).landmarks)})}
async function record(){if(units.some(u=>!u.stream))return $("#systemStatus").textContent="先に2台のカメラを開始してください";state.rows=[];units.forEach(u=>{u.samples=[];u.trail=[];u.beginRecord()});state.startTime=performance.now();state.recording=true;$("#record").disabled=true;$("#stop").disabled=false;$("#systemStatus").textContent=`Trial ${$("#trialNumber").value} 記録中`;$("#statusDot").classList.add("recording")}
async function stop(){state.recording=false;const blobs=await Promise.all(units.map(u=>u.finishRecord()));$("#record").disabled=false;$("#stop").disabled=true;$("#play").disabled=false;$("#seek").disabled=false;$("#exportCsv").disabled=state.rows.length===0;$("#downloadVideos").disabled=!blobs.some(Boolean);$("#statusDot").classList.remove("recording");$("#systemStatus").textContent=`Trial ${$("#trialNumber").value} 記録完了`;blobs.forEach((blob,i)=>{if(blob){const replay=$(`#replay${units[i].id}`);replay.src=URL.createObjectURL(blob);replay.playbackRate=+$("#speed").value}});if(state.mode==="terminal")$("#replaySection").hidden=false;units.forEach(u=>{if(u.samples.length)u.render(u.samples.at(-1).landmarks)});updateChart()}
function togglePlay(){const videos=[$("#replayA"),$("#replayB")];if(videos[0].paused){videos.forEach(v=>v.play());$("#play").textContent="❚❚ PAUSE"}else{videos.forEach(v=>v.pause());$("#play").textContent="▶ PLAY"}}
function syncReplay(){const a=$("#replayA"),b=$("#replayB");if(Math.abs(a.currentTime-b.currentTime)>.12)b.currentTime=a.currentTime;$("#seek").value=a.duration?Math.round(a.currentTime/a.duration*1000):0;$("#timecode").textContent=formatTime(a.currentTime);drawReplay(a.currentTime*1000)}
function drawReplay(ms){units.forEach(u=>{const sample=u.samples.reduce((best,s)=>Math.abs(s.t-ms)<Math.abs(best.t-ms)?s:best,u.samples[0]);if(!sample)return;const c=$(`[data-replay="${u.id}"]`),v=$(`#replay${u.id}`);c.width=v.videoWidth||1280;c.height=v.videoHeight||720;if(state.toggles.skeleton)draw(c,sample.landmarks)})}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String((s%60).toFixed(1)).padStart(4,"0")}`}
function updateCount(){$("#sampleCount").textContent=`${units.reduce((n,u)=>n+u.samples.length,0)} samples`}
let lastChart=0;function updateChart(){const now=performance.now();if(now-lastChart<100)return;lastChart=now;const c=$("#chart"),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext("2d");ctx.scale(dpr,dpr);ctx.fillStyle="#0b0d0f";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#262c2f";ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,h*i/4);ctx.lineTo(w,h*i/4);ctx.stroke()}const key=$("#graphVariable").value;$("#chartTitle").textContent=$("#graphVariable").selectedOptions[0].textContent;const all=units.flatMap(u=>u.samples.slice(-300).map(s=>s.metrics[key]));if(!all.length)return;let min=Math.min(...all),max=Math.max(...all);if(min===max){min-=1;max+=1}units.forEach((u,ui)=>{const data=u.samples.slice(-300);ctx.strokeStyle=ui?"#66e1ef":"#c9ff39";ctx.lineWidth=2;ctx.beginPath();data.forEach((s,i)=>{const x=i/Math.max(1,data.length-1)*w,y=h-(s.metrics[key]-min)/(max-min)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function exportCsv(){const headers=["timestamp","elapsed_ms","trial","condition","memo","camera","view","knee_angle","hip_angle","trunk_inclination","tracking_x","tracking_y","asymmetry","landmarks"];const lines=[headers.join(","),...state.rows.map(r=>[r.timestamp,r.elapsed_ms,r.trial,r.feedback_condition,r.memo,r.camera,r.view,r.knee,r.hip,r.trunk,r.trackingX,r.trackingY,r.asymmetry,r.landmarks].map(csvCell).join(","))];download(new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"}),`vbf_trial_${$("#trialNumber").value}.csv`)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

$("#startCameras").addEventListener("click",startAll);$("#refreshDevices").addEventListener("click",()=>devices(true).catch(e=>$("#systemStatus").textContent=e.message));units.forEach(u=>u.view.addEventListener("change",()=>u.viewChanged()));
$$('.feedback-mode button').forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));$("#condition").addEventListener("change",()=>setMode(modeFromCondition()));$$('[data-toggle]').forEach(input=>input.addEventListener("change",()=>{state.toggles[input.dataset.toggle]=input.checked;units.forEach(u=>u.values&&u.render(u.samples.at(-1).landmarks))}));
[$("#targetValue"),$("#tolerance")].forEach(input=>input.addEventListener("input",()=>{const v=+$("#targetValue").value,t=+$("#tolerance").value;$("#targetRange").textContent=`${v-t}–${v+t}°`}));$("#graphVariable").addEventListener("change",updateChart);
$("#record").addEventListener("click",record);$("#stop").addEventListener("click",stop);$("#play").addEventListener("click",togglePlay);$("#speed").addEventListener("change",()=>[$("#replayA"),$("#replayB")].forEach(v=>v.playbackRate=+$("#speed").value));$("#seek").addEventListener("input",()=>{const a=$("#replayA"),time=a.duration*+$("#seek").value/1000;[$("#replayA"),$("#replayB")].forEach(v=>v.currentTime=time)});$("#replayA").addEventListener("timeupdate",syncReplay);$("#closeReplay").addEventListener("click",()=>$("#replaySection").hidden=true);$("#exportCsv").addEventListener("click",exportCsv);$("#downloadVideos").addEventListener("click",()=>units.forEach(u=>state.blobs[u.id]&&download(state.blobs[u.id],`trial_${$("#trialNumber").value}_camera_${u.id}.webm`)));
navigator.mediaDevices?.addEventListener("devicechange",()=>devices(false));devices(false).catch(()=>{});updateChart();
