import { FilesetResolver, PoseLandmarker } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm";
const MODEL="https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm";
export const CONNECTIONS=PoseLandmarker.POSE_CONNECTIONS;
export async function createPose(){const vision=await FilesetResolver.forVisionTasks(WASM);return PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL,delegate:"GPU"},runningMode:"VIDEO",numPoses:1,minPoseDetectionConfidence:.55,minTrackingConfidence:.55})}
function angle(a,b,c){const ab={x:a.x-b.x,y:a.y-b.y},cb={x:c.x-b.x,y:c.y-b.y};const cosine=(ab.x*cb.x+ab.y*cb.y)/(Math.hypot(ab.x,ab.y)*Math.hypot(cb.x,cb.y));return Math.round(Math.acos(Math.max(-1,Math.min(1,cosine)))*180/Math.PI)}
export function measure(p){const side=((p[11].visibility??0)+(p[23].visibility??0)+(p[25].visibility??0))>=((p[12].visibility??0)+(p[24].visibility??0)+(p[26].visibility??0))?0:1;const s=p[11+side],h=p[23+side],k=p[25+side],a=p[27+side];return{knee:angle(h,k,a),hip:angle(s,h,k),trunk:Math.round(Math.atan2(Math.abs(s.x-h.x),Math.abs(s.y-h.y))*180/Math.PI)}}
export function draw(canvas,p){const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=Math.max(2,canvas.width/260);ctx.lineCap="round";for(const{start,end}of CONNECTIONS){if(start<11||end<11)continue;const a=p[start],b=p[end];if((a.visibility??1)<.45||(b.visibility??1)<.45)continue;ctx.strokeStyle="rgba(201,255,57,.82)";ctx.beginPath();ctx.moveTo(a.x*canvas.width,a.y*canvas.height);ctx.lineTo(b.x*canvas.width,b.y*canvas.height);ctx.stroke()}p.forEach((v,i)=>{if(i<11||(v.visibility??1)<.45)return;ctx.fillStyle=[23,24,25,26,27,28].includes(i)?"#c9ff39":"#f2f1eb";ctx.beginPath();ctx.arc(v.x*canvas.width,v.y*canvas.height,Math.max(3,canvas.width/180),0,Math.PI*2);ctx.fill()})}
export function setMetrics(root,v){for(const[k,n]of Object.entries(v)){const el=root.querySelector(`[data-metric="${k}"]`);if(el)el.innerHTML=`${n}<small>°</small>`;const bar=root.querySelector(`[data-bar="${k}"]`);if(bar)bar.style.width=`${Math.min(100,k==="trunk"?n*2:n/1.8)}%`}}
export async function getCamera(constraints){return Promise.race([navigator.mediaDevices.getUserMedia(constraints),new Promise((_,r)=>setTimeout(()=>r(new Error("カメラが応答しません")),12000))])}
